# -*- coding: utf-8 -*-
"""streamlit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uX7KILQqtQIFZcwlME2GoPFRDB70pYqP
"""

!pip install -q streamlit

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

!unzip ngrok-stable-linux-amd64.zip

! /content/ngrok authtoken 2IAwj52LWgvRZTm9FRMntJjVSMO_MzjLAFeDPV8y8DT8G5F5

get_ipython().system_raw('./ngrok http 8501 &')

!curl -s http://localhost:4040/api/tunnels | python3 -c \
    'import sys, json; print("Execute the next cell and the go to the following URL: " +json.load(sys.stdin)["tunnels"][0]["public_url"])'

!streamlit run /content/heroku.py

!pip3 freeze > requirements.txt